import type { Metadata } from "next";
import { Bricolage_Grotesque, Manrope } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "./providers";

const manrope = Manrope({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const bricolage_grotesque = Bricolage_Grotesque({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} ${bricolage_grotesque.variable} font-Manrope text-[#595959]  `}
      >
        <ReactQueryProvider> {children}</ReactQueryProvider>
      </body>
    </html>
  );
}
